// 引入 Next.js 类型定义
import type { Metadata } from 'next'
// 引入 Google 字体 Geist 和 Geist_Mono
import { Geist, Geist_Mono } from 'next/font/google'
// 引入全局样式
import './globals.css'

// 配置 Geist Sans 字体，设置 CSS 变量，应用于全局
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

// 配置 Geist Mono 字体，设置 CSS 变量，应用于全局
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// 全局的元数据（标题和描述），可用于 SEO
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// 根布局组件，用于包裹所有页面
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      {/* 应用自定义字体相关的 CSS 变量，并加上更平滑字体显示（antialiased） */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* 渲染传入的页面内容 */}
        {children}
      </body>
    </html>
  )
}
